### ISSUE TITLE
AttributeError: 'NanoPBOptions' object has no attribute 'mangle_names'

### ISSUE THREAD

**Issue by C47D** [nanopb/nanopb#341]
**Steps to reproduce the issue**

1. (nanopb commit i'm using is 3db8560, protoc version is libprotoc 3.6.1) and the following message:
```
# message.proto
syntax = "proto2"

message Example {
   required int32 value = 1;
}
```
2. protoc -o message.pb message.proto
3. python nanopb\generator\nanopb_generator.py message.pb

**What happens?**
> Traceback (most recent call last):
  File "C:\Users\Ingenieria6\Documents\nanopb\generator\nanopb_generator.py", line 1788, in <module>
    main_cli()
  File "C:\Users\Ingenieria6\Documents\nanopb\generator\nanopb_generator.py", line 1707, in main_cli
    results = process_file(filename, None, options)
  File "C:\Users\Ingenieria6\Documents\nanopb\generator\nanopb_generator.py", line 1648, in process_file
    f = parse_file(filename, fdesc, options)
  File "C:\Users\Ingenieria6\Documents\nanopb\generator\nanopb_generator.py", line 1630, in parse_file
    f = ProtoFile(fdesc, file_options)
  File "C:\Users\Ingenieria6\Documents\nanopb\generator\nanopb_generator.py", line 1123, in __init__
    self.parse()
  File "C:\Users\Ingenieria6\Documents\nanopb\generator\nanopb_generator.py", line 1134, in parse
    mangle_names = self.file_options.mangle_names
AttributeError: 'NanoPBOptions' object has no attribute 'mangle_names'

**What should happen?**
Files message.pb.h and message.pb.c generated.

**Comment by C47D** [comment]
> 
> 
> Maybe you've updated to new git revision but haven't run `make` in `generator/proto` directory?

Thanks for the quick reply, indeed, running make in the generator/proto dir was the solution.
