### ISSUE TITLE
CMake examples fail to build

### ISSUE THREAD

**Issue by TCatshoek** [nanopb/nanopb#476]
I am unable to build both the cmake examples included in the binary linux package.

cmake_simple outputs:
```
[ 11%] Running C++ protocol buffer compiler using nanopb plugin on simple.proto

         ********************************************************************
         *** Failed to import the protocol definitions for generator.     ***
         *** You have to run 'make' in the nanopb/generator/proto folder. ***
         ********************************************************************
    
Traceback (most recent call last):
  File "/home/tom/Projects/ProtoLink/protobuf/nanopb_bin/examples/cmake_simple/build/nanopb/generator/nanopb_generator.py", line 42, in <module>
    from .proto import nanopb_pb2
ImportError: attempted relative import with no known parent package
--nanopb_out: protoc-gen-nanopb: Plugin failed with status code 1.
make[2]: *** [CMakeFiles/simple.dir/build.make:63: simple.pb.c] Error 1
make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/simple.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

cmake_relpath outputs:
```
[  9%] Generating nanopb/generator/nanopb_generator.py, nanopb/generator/proto/nanopb.proto
[ 18%] Generating nanopb/generator/proto/nanopb_pb2.py
[ 27%] Running C++ protocol buffer compiler using nanopb plugin on proto/simple.proto
proto: warning: directory does not exist.

         ********************************************************************
         *** Failed to import the protocol definitions for generator.     ***
         *** You have to run 'make' in the nanopb/generator/proto folder. ***
         ********************************************************************
    
Traceback (most recent call last):
  File "/home/tom/Projects/ProtoLink/protobuf/nanopb_bin/examples/cmake_relpath/build/nanopb/generator/nanopb_generator.py", line 42, in <module>
    from .proto import nanopb_pb2
ImportError: attempted relative import with no known parent package
--nanopb_out: protoc-gen-nanopb: Plugin failed with status code 1.
make[2]: *** [CMakeFiles/simple.dir/build.make:63: simple.pb.c] Error 1
make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/simple.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

The "simple" example using just make builds and runs fine. 

Running make like the message says `make: Nothing to be done for 'all'.
`

I'm on arch, running python 3.8.1, if that is relevant.

**Comment by TCatshoek** [comment]
Probably the same issue as https://github.com/nanopb/nanopb/issues/470

Can confirm the examples build fine using the latest version from the repo.

I'm still getting the same error in my own project though. Will try to figure this out tomorrow.

**Comment by TCatshoek** [comment]
Apparently cmake was caching the old nanopb_generator.py in my own project, it's fixed now!
