### ISSUE TITLE
problem generating with nested messages and default values

### ISSUE THREAD

**Issue by matejcik** [nanopb/nanopb#487]
the following proto file will fail
```protobuf
syntax = "proto2";
package a.b.c;

message TopLevel {
    optional uint32 field = 1 [default = 0];
    optional NestedTypeA foo = 2;

    message NestedTypeA {
        optional NestedTypeB bar = 1;

        message NestedTypeB {
            optional uint32 foobar = 1;
        }
    }
}
```
```
$ nanopb_generator test.proto
Traceback (most recent call last):
  File "/home/matejcik/.virtualenvs/trezor/bin/nanopb_generator", line 10, in <module>
    sys.exit(main_cli())
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/nanopb/generator/nanopb_generator.py", line 1929, in main_cli
    results = process_file(fdesc.name, fdesc, options, other_files)
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/nanopb/generator/nanopb_generator.py", line 1866, in process_file
    headerdata = ''.join(f.generate_header(includes, headerbasename, options))
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/nanopb/generator/nanopb_generator.py", line 1523, in generate_header
    yield msg.fields_declaration(self.dependencies) + '\n'
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/nanopb/generator/nanopb_generator.py", line 1092, in fields_declaration
    defval = self.default_value(dependencies)
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/nanopb/generator/nanopb_generator.py", line 1209, in default_value
    desc = google.protobuf.descriptor.MakeDescriptor(optional_only)
  File "/home/matejcik/.virtualenvs/trezor/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 1015, in MakeDescriptor
    _message.default_pool.Add(file_descriptor_proto)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "56c5817fd17751bb1700a9b56f9d6b93.proto":
  TopLevel.NestedTypeA.bar: ".a.b.c.TopLevel.NestedTypeA.NestedTypeB" is not defined.
```

to make it more fun, in Python 3.8 it works (for me at least), because protobuf's C++ extension is unavailable and the Python implementation seems to care less about `type_name`s?

AFAICT, the problem is that the `optional_only`  descriptor carries nested type information, which doesn't seem to be necessary. The problem goes away when I add   `optional_only.ClearField(str('nested_type'))` in [here](https://github.com/nanopb/nanopb/blob/master/generator/nanopb_generator.py#L1208)

not sure if that's the correct solution though

**Comment by PetteriAimonen** [comment]
Thanks, I added your fix now, it's at least better than before.

I think there needs to be some better way to do the default_value(), the protobuf-python reflection API seems too fragile between versions and there have been many similar bugs already.
