### ISSUE TITLE
Calling nanopb_generator.py without --output_dir fails since 0.4.2

### ISSUE THREAD

**Issue by PetteriAimonen** [nanopb/nanopb#553]
Originally reported in https://stackoverflow.com/questions/62601540/nanopb-failing-to-encode

Fix for #512 in commit 5572456697d0fa caused a regression which gives error:

<pre>
Traceback (most recent call last):
  File "generator/nanopb_generator.py", line 2122, in <module>
    main_cli()
  File "generator/nanopb_generator.py", line 2034, in main_cli
    os.makedirs(os.path.dirname(path), exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
</pre>

A workaround is to specify `--output_dir=.`.

**Comment by PetteriAimonen** [comment]
Also related bug: generator writes files for all the dependencies also, even if they were not passed to the generator directly.
