### ISSUE TITLE
Import "nanopb.proto" has not been loaded.

### ISSUE THREAD

**Issue by raczben** [nanopb/nanopb#618]
I got this runtime error:

```console
~/work/build/mypkg(proto*) » python ./test1.py
Traceback (most recent call last):
  File "../test1.py", line 12, in <module>
    import mypkg.my_api as my_api 
  File "/home/raczb/work/build/mypkg/my_api .py", line 22, in <module>
    import mypkg.proto.my_proto_pb2 as my_proto_pb2 
  File "/home/raczb/work/mypkg/proto/my_proto_pb2.py", line 25, in <module>
    dependencies=[nanopb__pb2.DESCRIPTOR,])
  File "/home/raczb/work/.env/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 829, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "proto/my_proto.proto":
  proto/ymir.proto: Import "nanopb.proto" has not been loaded.
```

after build:

```console
protoc -I.:ext/nanopb/generator/proto/ --python_out=mypkg proto/my_proto.proto
protoc -I.:ext/nanopb/generator/proto/ --python_out=mypkg proto/nanopb.proto
```

It works only with `protobuf==3.1` any other protobuf throws this exception

**Comment by PetteriAimonen** [comment]
Seems like some kind of problem with Python protobuf libraries. One can put the nanopb options in separate `.options` file, if including `nanopb.proto` causes problems.
