### ISSUE TITLE
nanopb_generate.py unable to resolve dependency when called standalone

### ISSUE THREAD

**Issue by nslogan** [nanopb/nanopb#714]
**Steps to reproduce the issue**

Tools:
- `nanopb_generator.py` from tag 0.4.5, installed using cmake
- `protoc` version 3.13.0

```protobuf
# ./mod_a.proto
syntax = "proto2";
package com.example;

enum ExampleEnum {
  EXAMPLE_UNKNOWN_VALUE = 0x00;
  EXAMPLE_A             = 0x01;
}
```

```protobuf
# ./mod_b.proto
syntax = "proto2";

package com.example;

import "mod_a.proto";

message ExampleMsg {
  required com.example.ExampleEnum enum_val = 1;
}
```

Using `nanopb_generator.py` by itself does not work:

```bash
nanopb_generator.py mod_b.proto

Traceback (most recent call last):
  File "/usr/bin/nanopb_generator.py", line 1439, in default_value
    enumtype = dependencies[str(enumname)]
KeyError: 'com_example_ExampleEnum'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/nanopb_generator.py", line 2340, in <module>
    main_cli()
  File "/usr/bin/nanopb_generator.py", line 2228, in main_cli
    results = process_file(fdesc.name, fdesc, options, other_files)
  File "/usr/bin/nanopb_generator.py", line 2158, in process_file
    headerdata = ''.join(f.generate_header(includes, headerbasename, options))
  File "/usr/bin/nanopb_generator.py", line 1788, in generate_header
    yield msg.fields_declaration(self.dependencies) + '\n'
  File "/usr/bin/nanopb_generator.py", line 1331, in fields_declaration
    defval = self.default_value(dependencies)
  File "/usr/bin/nanopb_generator.py", line 1441, in default_value
    raise Exception("Could not find enum type %s while generating default values for %s.\n" % (enumname, self.name)
Exception: Could not find enum type com_example_ExampleEnum while generating default values for com_example_ExampleMsg.
Try passing all source files to generator at once, or use -I option.
```

But using it as a plugin works:

```bash
protoc --plugin=protoc-gen-nanopb=/usr/bin/protoc-gen-nanopb --nanopb_out=. mod_b.proto
# Files properly generated
```

**What happens?**

Using `nanopb_generator.py` standalone is unable to resolve a dependency unless the dependency is passed alongside the target file, e.g.:

```bash
nanopb_generator.py mod_b.proto mod_a.proto
```

But this is unnecessary when `nanopb_generator.py` is used as a plugin (via `protoc-gen-nanopb`).

**What should happen?**

I would expect `nanopb_generator.py` to have similar behavior to `protoc` with the nanopb plugin, but maybe I am misunderstanding the purpose of the standalone generator. Clarifying the difference between generating with `protoc` vs. `nanopb_generator.py` would be helpful.

Thanks!

**Comment by PetteriAimonen** [comment]
This turned out to be a regression introduced in 0.4.3 and it was fixed in #720, fix is going into 0.4.6.
