### ISSUE TITLE
cmake_simple example fails to compile

### ISSUE THREAD

**Issue by shrkamat** [nanopb/nanopb#860]
```
skamath@thinkpad:~/Projects/proto/nanopb/examples/cmake_simple$ mkdir -p build && cd build
skamath@thinkpad:~/Projects/proto/nanopb/examples/cmake_simple/build$ cmake ..
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Nanopb: /usr/local/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/skamath/Projects/proto/nanopb/examples/cmake_simple/build
skamath@thinkpad:~/Projects/proto/nanopb/examples/cmake_simple/build$ make VERBOSE=1
/home/skamath/.sysroot/bin/cmake -S/home/skamath/Projects/proto/nanopb/examples/cmake_simple -B/home/skamath/Projects/proto/nanopb/examples/cmake_simple/build --check-build-system CMakeFiles/Makefile.cmake 0
/home/skamath/.sysroot/bin/cmake -E cmake_progress_start /home/skamath/Projects/proto/nanopb/examples/cmake_simple/build/CMakeFiles /home/skamath/Projects/proto/nanopb/examples/cmake_simple/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/skamath/Projects/proto/nanopb/examples/cmake_simple/build'
make  -f CMakeFiles/simple.dir/build.make CMakeFiles/simple.dir/depend
make[2]: Entering directory '/home/skamath/Projects/proto/nanopb/examples/cmake_simple/build'
[ 11%] Generating nanopb/generator/nanopb_generator.py, nanopb/generator/proto/nanopb.proto
/home/skamath/.sysroot/bin/cmake -E copy_directory /usr/local/bin/ /home/skamath/Projects/proto/nanopb/examples/cmake_simple/build/nanopb/generator
[ 22%] Generating nanopb/generator/proto/nanopb_pb2.py
/usr/bin/protoc -I/home/skamath/Projects/proto/nanopb/examples/cmake_simple/build/nanopb/generator/proto --python_out=/home/skamath/Projects/proto/nanopb/examples/cmake_simple/build/nanopb/generator/proto /home/skamath/Projects/proto/nanopb/examples/cmake_simple/build/nanopb/generator/proto/nanopb.proto
/home/skamath/Projects/proto/nanopb/examples/cmake_simple/build/nanopb/generator/proto: warning: directory does not exist.
/home/skamath/Projects/proto/nanopb/examples/cmake_simple/build/nanopb/generator/proto/nanopb.proto: No such file or directory
make[2]: *** [CMakeFiles/simple.dir/build.make:82: nanopb/generator/proto/nanopb_pb2.py] Error 1
make[2]: Leaving directory '/home/skamath/Projects/proto/nanopb/examples/cmake_simple/build'
make[1]: *** [CMakeFiles/Makefile2:82: CMakeFiles/simple.dir/all] Error 2
make[1]: Leaving directory '/home/skamath/Projects/proto/nanopb/examples/cmake_simple/build'
make: *** [Makefile:91: all] Error 2
```

**Comment by shrkamat** [comment]
#### my environment

```
skamath@thinkpad:~/Projects/proto/nanopb/examples/cmake_simple$ uname -a
Linux thinkpad 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
skamath@thinkpad:~/Projects/proto/nanopb/examples/cmake_simple$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
skamath@thinkpad:~/Projects/proto/nanopb/examples/cmake_simple$ which python3
/usr/bin/python3
skamath@thinkpad:~/Projects/proto/nanopb/examples/cmake_simple$ pip list | grep protobuf
protobuf               3.6.1

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python -m pip install --upgrade pip
skamath@thinkpad:~/Projects/proto/nanopb/examples/cmake_simple$ dpkg -l | grep protobuf
ii  libprotobuf-dev:amd64                      3.6.1.3-2ubuntu5.2                                                        amd64        protocol buffers C++ library (development files) and proto files
ii  libprotobuf-lite17:amd64                   3.6.1.3-2ubuntu5.2                                                        amd64        protocol buffers C++ library (lite version)
ii  libprotobuf17:amd64                        3.6.1.3-2ubuntu5.2                                                        amd64        protocol buffers C++ library
ii  protobuf-compiler                          3.6.1.3-2ubuntu5.2                                                        amd64        compiler for protocol buffer definition files
ii  python3-protobuf                           3.6.1.3-2ubuntu5.2                                                        amd64        Python 3 bindings for protocol buffers
```

#### some debugging
```
python3 -m pip install protobuf
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: protobuf in /usr/lib/python3/dist-packages (3.6.1)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python3 -m pip install --upgrade pip
skamath@thinkpad:~/Projects/proto/nanopb/examples/cmake_simple$ python3
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import proto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'proto'
```

**Comment by shrkamat** [comment]
#### my environment
```
skamath@thinkpad:~/Projects/proto/nanopb/examples/cmake_simple$ uname -a
Linux thinkpad 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
skamath@thinkpad:~/Projects/proto/nanopb/examples/cmake_simple$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
skamath@thinkpad:~/Projects/proto/nanopb/examples/cmake_simple$ which python3
/usr/bin/python3
skamath@thinkpad:~/Projects/proto/nanopb/examples/cmake_simple$ pip list | grep protobuf
protobuf               3.6.1

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python -m pip install --upgrade pip
skamath@thinkpad:~/Projects/proto/nanopb/examples/cmake_simple$ dpkg -l | grep protobuf
ii  libprotobuf-dev:amd64                      3.6.1.3-2ubuntu5.2                                                        amd64        protocol buffers C++ library (development files) and proto files
ii  libprotobuf-lite17:amd64                   3.6.1.3-2ubuntu5.2                                                        amd64        protocol buffers C++ library (lite version)
ii  libprotobuf17:amd64                        3.6.1.3-2ubuntu5.2                                                        amd64        protocol buffers C++ library
ii  protobuf-compiler                          3.6.1.3-2ubuntu5.2                                                        amd64        compiler for protocol buffer definition files
ii  python3-protobuf                           3.6.1.3-2ubuntu5.2                                                        amd64        Python 3 bindings for protocol buffers
```
#### some debugging
```
python3 -m pip install protobuf
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: protobuf in /usr/lib/python3/dist-packages (3.6.1)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python3 -m pip install --upgrade pip
skamath@thinkpad:~/Projects/proto/nanopb/examples/cmake_simple$ python3
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import proto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'proto'
```

**Comment by shrkamat** [comment]
@PetteriAimonen  Would cmake version make a difference ? I am using `cmake version 3.22.1` not default version from distribution.

**Comment by shrkamat** [comment]
Now this works, from `cmake_simple/build` dir

```
mkdir -p nanopb
cp -rvf ../../../generator nanopb/
make
[ 11%] Generating nanopb/generator/proto/nanopb_pb2.py
[ 22%] Running C++ protocol buffer compiler using nanopb plugin on simple.proto
[ 33%] Building C object CMakeFiles/simple.dir/simple.c.o
[ 44%] Building C object CMakeFiles/simple.dir/simple.pb.c.o
[ 55%] Building C object CMakeFiles/simple.dir/home/skamath/Projects/proto/nanopb/pb_decode.c.o
[ 66%] Building C object CMakeFiles/simple.dir/home/skamath/Projects/proto/nanopb/pb_encode.c.o
[ 77%] Building C object CMakeFiles/simple.dir/home/skamath/Projects/proto/nanopb/pb_common.c.o
[ 88%] Linking C executable simple
[100%] Built target simple
```

Is this step expected ?

**Comment by PetteriAimonen** [comment]
I think the CMake rules should do that automatically.
I have cmake 3.16.3, but I think the github workflow runs tests on something newer also.

I don't know much about CMake myself.

**Comment by PetteriAimonen** [comment]
I cannot reproduce this problem myself.
