### ISSUE TITLE
cannot generate sources

### ISSUE THREAD

**Issue by basiliscos** [nanopb/nanopb#966]
```
-> % python --version
Python 3.12.1

/usr/bin/python ../generator/nanopb_generator.py simple/simple.proto
/tmp/nanopb-0.3.9.10/examples/../generator/nanopb_generator.py:1497: SyntaxWarning: invalid escape sequence '\*'
  data = re.sub('/\*.*?\*/', '', data, flags = re.MULTILINE)
/tmp/nanopb-0.3.9.10/examples/../generator/nanopb_generator.py:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources # pyinstaller / protobuf 2.5 seem to need these
Traceback (most recent call last):
  File "/tmp/nanopb-0.3.9.10/examples/../generator/nanopb_generator.py", line 1844, in <module>
    main_cli()
  File "/tmp/nanopb-0.3.9.10/examples/../generator/nanopb_generator.py", line 1740, in main_cli
    results = process_file(filename, None, options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/nanopb-0.3.9.10/examples/../generator/nanopb_generator.py", line 1676, in process_file
    f = parse_file(filename, fdesc, options)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/nanopb-0.3.9.10/examples/../generator/nanopb_generator.py", line 1627, in parse_file
    fdesc = descriptor.FileDescriptorSet.FromString(data).file[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
google.protobuf.message.DecodeError: Error parsing message with type 'google.protobuf.FileDescriptorSet'

```

**Comment by PetteriAimonen** [comment]
Seems like there are two issues:

1. Some warnings related to new Python version. I think these are fixed in newest git version, but I'm currently not planning to backport the updates to 0.3.9.x as they are just warnings.

2. The `nanopb_generator.py` in the 0.3.9.x series does not support calling directly with a `.proto` file. You can either use it as `protoc` plugin, or to process a file generated by `protoc -ofoo.pb`.

Relevant documents for 0.3.9.x:
https://github.com/nanopb/nanopb/blob/maintenance_0.3/README.md
https://github.com/nanopb/nanopb/blob/maintenance_0.3/docs/index.rst#getting-started

If this is a new project, I would strongly suggest starting with the nanopb-0.4 version. For past five years, 0.3.9.x has only received bug fix updates.
